ENGINE: #For this section ensure none of the keys are missing
  epochs: 150
  save_loc: ./results #Empty save loc indicates no save location
  resume_loc: #Empty resume loc indicates no need to resume
  transfer_loc: 
  save_freq: 30
  gpu_devices: [0]
  use_dataparallel: false
  location_mod:
  random_seed: 0

METRIC:
  subclass_name: dgi
  n_classes: 7

MODEL:
  subclass_name: multiview_contrast_sample_v2
  out_channel: 256
  num_samples: 500
  proc_percent: 0.5
  sample_proc: bottom
  cellgraph_params:
    cellgraph_name: GNN_ASAP_bn
    out_channel: 256
    in_channel: 518
    hidden_channel: 256
    num_gc_layers: 4
    batch_norm: true
    pooling: false
  patchgraph_params:
    patchgraph_name: GNN_ASAP_bn
    out_channel: 256
    in_channel: 512
    hidden_channel: 522
    num_gc_layers: 4
    batch_norm: true
    pooling: false

DATASET:
  subclass_name: multiview_data
  path: ./BRACS_dataset_prev
  class_name_list: ["0_N", "1_PB", "2_UDH", "3_ADH", "4_FEA", "5_DCIS", "6_IC"]
  feat_folder_cell: graph_obj_simclr_v2
  feat_folder_patch: patch_graph_custom_simclr
  add_pos: false
  train_batch_size: 32
  test_batch_size: 32

LOGGER:
  subclass_name: 
  use_wandb: true
  watch_gradients: false 
  project_name: BRACS_final
  run_name: multiview_contrast_bot_v2
  notes: Multiview contrast, save model, sample randomly from cg nodes for pg to cg
  tags: ["multiview","contrast","seed"]

#not used here but still defining so as to not break the code
LOSS:
  module_name: torch.nn
  subclass_name: CrossEntropyLoss

OPTIMIZER:
  module_name: torch.optim
  subclass_name: Adam
  lr: 0.0001
  weight_decay: 0.00001

SCHEDULER:
  epoch_wise: false
  module_name: torch.optim.lr_scheduler
  subclass_name: CyclicLR
  mode: triangular
  cycle_momentum: false
  step_size_up: 150
  base_lr: 0.00001
  max_lr: 0.0001